### ISSUE TITLE
A small question，please

### ISSUE THREAD

**Issue by DragonM096** [littlejuyan/FusingGlobalandLocal#1]
In line 102 of base_options.py, opt. classes=opt. classes. split (','), an error message indicates that  'Namespace' object has no attribute 'classes'.There is indeed no parameter 'classes' in your option code. How do you define this' classes'?
If you could reply to me amidst your busy schedule, I would be extremely grateful~
![111](https://github.com/littlejuyan/FusingGlobalandLocal/assets/73045158/0e757ff8-2f69-42f3-b347-84b8b394b6b7)

**Comment by peihuan494** [comment]
I have encountered the same problem, how did you solve it? I would be very grateful if you could reply me in your busy schedule
